# Values used to generate this template

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  project_description: "{{ cookiecutter.project_description }}"
  license: "{{ cookiecutter.license }}"
  minimal_python_version: "{{ cookiecutter.minimal_python_version }}"
  author_name: "{{ cookiecutter.author_name }}"
  author_email: "{{ cookiecutter.author_email }}"
  version: "{{ cookiecutter.version }}"
  line_length: "{{ cookiecutter.line_length }}"
  create_example_template: "{{ cookiecutter.create_example_template }}"
  additional_content: "{{ cookiecutter.additional_content }}"
